[project]
name = "comfyui-daz-tools"
description = "A collection of utility nodes: Workflow Managers for WAN2.2, LTX2.3, LTX2.5 and MiniMax H3 - all in-one -movie- setups that you can organize in scenes, takes, etc; A prompt stack node to organize and save your prompts; Audio Mixer - mix audio on a visual tool, matching video frames, and enhance your video audio tracks!; Tools for null checking and more!"
version = "4.1.1"
license = "MIT"
requires-python = ">=3.10"

classifiers = [
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/denyazzolin/comfyui-daz-tools"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/denyazzolin/comfyui-daz-tools/wiki"
"Bug Tracker" = "https://github.com/denyazzolin/comfyui-daz-tools/issues"

[tool.comfy]
PublisherId = "denyazzolin"
DisplayName = "ComfyUI Daz Tools"
Icon = "https://raw.githubusercontent.com/denyazzolin/comfyui-daz-tools/master/content/DAZ.png"
includes = []
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
